# Generated by Django 5.2 on 2025-04-23 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogos_favoritos', models.CharField(max_length=255)),
                ('jogador_favorito', models.CharField(max_length=100)),
                ('tipo_de_conteudo', models.CharField(max_length=100)),
                ('nivel_engajamento', models.CharField(default='Neutro', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
