# Generated by Django 5.2 on 2025-04-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fanprofile',
            old_name='tipo_de_conteudo',
            new_name='tipo_conteudo',
        ),
        migrations.AddField(
            model_name='fanprofile',
            name='horas_assistidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fanprofile',
            name='interacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fanprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
