# Generated by Django 5.2 on 2025-04-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanprofile', '0002_rename_tipo_de_conteudo_fanprofile_tipo_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
