# Generated by Django 5.2 on 2025-04-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanprofile', '0003_fanprofile_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanprofile',
            name='horas_assistidas',
        ),
    ]
