# Generated by Django 5.2 on 2025-04-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanprofile', '0004_remove_fanprofile_horas_assistidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanprofile',
            name='nivel_engajamento',
        ),
    ]
