# Generated by Django 5.2 on 2025-04-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanprofile', '0006_fanprofile_tweets_relacionados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fanprofile',
            old_name='tweets_relacionados',
            new_name='tweets',
        ),
    ]
