# Generated by Django 5.2 on 2025-04-28 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanprofile', '0007_rename_tweets_relacionados_fanprofile_tweets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanprofile',
            name='tweets',
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.CharField(max_length=255)),
                ('fanprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='fanprofile.fanprofile')),
            ],
        ),
    ]
