# Generated by Django 5.2 on 2025-04-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanprofile', '0008_remove_fanprofile_tweets_tweets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='data_criacao',
            new_name='data',
        ),
    ]
