# Generated by Django 5.2 on 2025-04-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanprofile', '0009_rename_data_criacao_tweets_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
