# Generated by Django 5.2 on 2025-04-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanprofile', '0010_alter_tweets_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
