# Generated by Django 5.2 on 2025-04-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanprofile', '0011_alter_tweets_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='data',
        ),
    ]
