# Generated by Django 5.2 on 2025-05-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanprofile', '0012_remove_tweets_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.ImageField(upload_to='medalhas/')),
                ('criterio', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='fanprofile',
            name='medalhas',
            field=models.ManyToManyField(blank=True, to='fanprofile.medalha'),
        ),
    ]
