# Generated by Django 5.2 on 2025-05-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanprofile', '0013_medalha_fanprofile_medalhas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medalha',
            name='icone',
            field=models.CharField(max_length=255),
        ),
    ]
